local ls = require("luasnip")
local s = ls.snippet

return {
  s({ trig = "ga", snippetType = "snippet" }, { t("\\alpha") }),
  s({ trig = "gb", snippetType = "snippet" }, { t("\\beta") }),
  s({ trig = "gg", snippetType = "snippet" }, { t("\\gamma") }),
  s({ trig = "gd", snippetType = "snippet" }, { t("\\delta") }),
  s({ trig = "ge", snippetType = "snippet" }, { t("\\varepsilon") }),
  s({ trig = "gee", snippetType = "snippet" }, { t("\\epsilon") }),
  s({ trig = "gz", snippetType = "snippet" }, { t("\\zeta") }),
  s({ trig = "gh", snippetType = "snippet" }, { t("\\eta") }),
  s({ trig = "gth", snippetType = "snippet" }, { t("\\theta") }),
  s({ trig = "gthv", snippetType = "snippet" }, { t("\\vartheta") }),
  s({ trig = "gi", snippetType = "snippet" }, { t("\\iota") }),
  s({ trig = "gk", snippetType = "snippet" }, { t("\\kappa") }),
  s({ trig = "gl", snippetType = "snippet" }, { t("\\lambda") }),
  s({ trig = "gm", snippetType = "snippet" }, { t("\\mu") }),
  s({ trig = "gn", snippetType = "snippet" }, { t("\\nu") }),
  s({ trig = "gx", snippetType = "snippet" }, { t("\\xi") }),
  s({ trig = "gc", snippetType = "snippet" }, { t("\\chi") }),
  s({ trig = "gp", snippetType = "snippet" }, { t("\\pi") }),
  s({ trig = "gr", snippetType = "snippet" }, { t("\\rho") }),
  s({ trig = "grr", snippetType = "snippet" }, { t("\\varrho") }),
  s({ trig = "gs", snippetType = "snippet" }, { t("\\sigma") }),
  s({ trig = "gt", snippetType = "snippet" }, { t("\\tau") }),
  s({ trig = "gu", snippetType = "snippet" }, { t("\\upsilon") }),
  s({ trig = "gf", snippetType = "snippet" }, { t("\\phi") }),
  s({ trig = "gff", snippetType = "snippet" }, { t("\\varphi") }),
  s({ trig = "gy", snippetType = "snippet" }, { t("\\psi") }),
  s({ trig = "go", snippetType = "snippet" }, { t("\\omega") }),
  -- capital letters
  s({ trig = "gE", snippetType = "snippet" }, { t("\\mathcal{E}") }),
  s({ trig = "gG", snippetType = "snippet" }, { t("\\Gamma") }),
  s({ trig = "gD", snippetType = "snippet" }, { t("\\Delta") }),
  s({ trig = "gTH", snippetType = "snippet" }, { t("\\Theta") }),
  s({ trig = "gL", snippetType = "snippet" }, { t("\\Lambda") }),
  s({ trig = "gX", snippetType = "snippet" }, { t("\\Xi") }),
  s({ trig = "gP", snippetType = "snippet" }, { t("\\Pi") }),
  s({ trig = "gS", snippetType = "snippet" }, { t("\\Sigma") }),
  s({ trig = "gU", snippetType = "snippet" }, { t("\\Upsilon") }),
  s({ trig = "gF", snippetType = "snippet" }, { t("\\Phi") }),
  s({ trig = "gY", snippetType = "snippet" }, { t("\\Psi") }),
  s({ trig = "gO", snippetType = "snippet" }, { t("\\Omega") }),
}
